/**
 * NativeProverService — thin wrapper over mopro-ffi's `generateCircomProof`
 * for the authorize circuit.
 *
 * Why this exists: the WebView path (ZKBridgeService + snarkjs inside
 * HiddenWebView) spikes the WebKit process CPU for ~1–2s per proof, and
 * on the iOS Simulator this starves the shared dispatch queue so that
 * every HTTP call dispatched right after the proof aborts at its
 * deadline — see the `OrderService` diagnostic logs in PR #408 and the
 * abort chain in #401/#404/#407. Running the prover as native code
 * removes the burst (arkworks/groth16 runs on a native thread) and with
 * it the NSURLSession stall.
 *
 * Scope: authorize only. Deposit/claim/cancel still route through the
 * WebView until this path is validated end-to-end; the router lives in
 * `ZKBridgeService.generateProof`.
 */
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
// `mopro-ffi` is a local file: dependency generated by `mobile/native-prover`.
// The generated TS calls into the Turbo Module on first import, which
// registers the Rust crate with Hermes. Keep this import module-scoped so
// that registration happens once per JS runtime (Metro hot-reloads will
// dedupe via the rustInstalled flag inside the package).
import { generateCircomProof, ProofLib } from 'mopro-ffi';

/** Resolved once, cached. The generated proof API needs a filesystem path
 *  (not a require()-returned asset number), so on the first call we make
 *  sure the asset is downloaded (expo-asset caches it in the app sandbox)
 *  and return its `localUri` without the `file://` scheme prefix — the
 *  Rust side passes the string to `std::fs::File::open`, which rejects
 *  URI-form paths. */
let cachedZkeyPath: string | null = null;

async function resolveAuthorizeZkeyPath(): Promise<string> {
  if (cachedZkeyPath) return cachedZkeyPath;
  const asset = Asset.fromModule(require('../../assets/zk-native/authorize_final.zkey'));
  await asset.downloadAsync();
  const uri = asset.localUri || asset.uri;
  if (!uri) throw new Error('authorize_final.zkey asset could not be resolved');
  // Some devices return the asset under `file://`, the native prover wants
  // a plain path. Strip the scheme and verify the file actually exists —
  // a missing asset here is a packaging bug, not a runtime network issue.
  const path = uri.replace(/^file:\/\//, '');
  const info = await FileSystem.getInfoAsync(path);
  if (!info.exists) throw new Error(`authorize_final.zkey not found at ${path}`);
  cachedZkeyPath = path;
  return path;
}

/** Shape matching `snarkjs.groth16.fullProve` so `formatProofForSolidity`
 *  and other downstream helpers keep working unchanged when this path is
 *  picked over the WebView one. */
export type SnarkjsLikeProofResult = {
  proof: {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
  };
  publicSignals: string[];
  elapsedMs: number;
};

/** Runs Groth16 proving for the `authorize` circuit natively. Input is
 *  the same JSON shape the circom circuit consumes — same as we pass to
 *  snarkjs on the WebView side — so the caller doesn't need to branch. */
export async function generateAuthorizeProof(
  inputs: Record<string, unknown>,
): Promise<SnarkjsLikeProofResult> {
  const zkeyPath = await resolveAuthorizeZkeyPath();
  const t0 = Date.now();
  // Arkworks is the only proof backend bundled today. Rapidsnark is
  // available as an alternative but not wired in — keep a single path
  // until benchmarks show it's worth the extra binary size.
  const res = generateCircomProof(zkeyPath, JSON.stringify(inputs), ProofLib.Arkworks);
  const elapsedMs = Date.now() - t0;
  // mopro returns G1/G2 points as {x,y,z} / {x:[],y:[],z:[]}. snarkjs
  // returns pi_a / pi_b / pi_c as flat arrays. Convert here so callers
  // can keep using `formatProofForSolidity` without branching.
  return {
    proof: {
      pi_a: [res.proof.a.x, res.proof.a.y, res.proof.a.z],
      pi_b: [
        [res.proof.b.x[0], res.proof.b.x[1]],
        [res.proof.b.y[0], res.proof.b.y[1]],
        [res.proof.b.z[0], res.proof.b.z[1]],
      ],
      pi_c: [res.proof.c.x, res.proof.c.y, res.proof.c.z],
    },
    publicSignals: res.inputs,
    elapsedMs,
  };
}
