/**
 * NativeProverService — thin wrapper over mopro-ffi's `generateCircomProof`
 * for the authorize circuit.
 *
 * Why this exists: the WebView path (ZKBridgeService + snarkjs inside
 * HiddenWebView) spikes the WebKit process CPU for ~1–2s per proof, and
 * on the iOS Simulator this starves the shared dispatch queue so that
 * every HTTP call dispatched right after the proof aborts at its
 * deadline — see the `OrderService` diagnostic logs in PR #408 and the
 * abort chain in #401/#404/#407. Running the prover as native code
 * removes the burst (arkworks/groth16 runs on a native thread) and with
 * it the NSURLSession stall.
 *
 * Scope: authorize only. Deposit/claim/cancel still route through the
 * WebView until this path is validated end-to-end; the router lives in
 * `ZKBridgeService.generateProof`.
 */
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
// `mopro-ffi` is a local file: dependency generated by `mobile/native-prover`.
// The generated TS calls into the Turbo Module on first import, which
// registers the Rust crate with Hermes. Keep this import module-scoped so
// that registration happens once per JS runtime (Metro hot-reloads will
// dedupe via the rustInstalled flag inside the package).
import { generateCircomProof, ProofLib } from 'mopro-ffi';

// `set_circom_circuits!` in `mobile/native-prover/src/lib.rs` keys the
// witness function on this exact basename — expo-asset's hashed filename
// fails the `Path::file_name()` match, so we copy under the original.
const ZKEY_FILENAME = 'authorize_final.zkey';

let cachedZkeyPath: string | null = null;

/** Resolves the bundled zkey to a plain filesystem path the Rust side can
 *  `std::fs::File::open`. The FFI path must not have a `file://` prefix —
 *  Rust's File::open rejects URI-form paths. */
async function resolveAuthorizeZkeyPath(): Promise<string> {
  if (cachedZkeyPath) return cachedZkeyPath;
  const asset = Asset.fromModule(require('../../assets/zk-native/authorize_final.zkey'));
  await asset.downloadAsync();
  // Require `localUri` specifically. `asset.uri` may still hold an
  // `http(s)://` (Metro dev server) or `asset:/` (Android asset
  // archive) URI that `expo-file-system.copyAsync` rejects — only the
  // post-download local file:// URI is safe to hand to `copyAsync`.
  const uri = asset.localUri;
  if (!uri || !uri.startsWith('file://')) {
    throw new Error(
      `${ZKEY_FILENAME} asset has no local file URI after downloadAsync (got ${String(uri)})`,
    );
  }
  // expo's `documentDirectory` is `null` until the FS module finishes
  // initializing; bail with a clear message rather than concatenating a
  // literal `nullauthorize_final.zkey` path that mopro will then reject.
  const docDir = FileSystem.documentDirectory;
  if (!docDir) throw new Error('expo-file-system documentDirectory unavailable');
  // Bust the destination cache when the bundled asset changes. expo-asset
  // hashes assets with a stable content hash; tagging the destination
  // filename with that hash means a `copy:circuits` rebuild lands as a
  // fresh file on next launch instead of silently reusing the previous
  // zkey. (Without this we shipped working WebView/native paths against
  // a verifier that had already moved on, and every authorize order
  // reverted with `InvalidProof()` 0x09bde339 at settle time.) Falling
  // back to the bare filename only if the asset has no hash keeps the
  // path stable for environments where expo-asset hasn't populated it.
  const tag = asset.hash ? `.${asset.hash}` : '';
  const destPath = `${docDir}${ZKEY_FILENAME}${tag}`;
  const destInfo = await FileSystem.getInfoAsync(destPath);
  if (!destInfo.exists) {
    // expo-file-system on Android requires URI-form paths (with the
    // `file://` scheme) for `copyAsync`; iOS accepts both. Strip the
    // scheme only when the resulting plain path crosses the FFI to Rust,
    // which uses `std::fs::File::open` and rejects URI-form input.
    await FileSystem.copyAsync({ from: uri, to: destPath });
  }
  cachedZkeyPath = destPath.replace(/^file:\/\//, '');
  return cachedZkeyPath;
}

/** circom-prover (the arkworks backend mopro uses) only parses decimal
 *  BigInt strings. snarkjs is lenient and accepts hex (`0x…`), which is
 *  why merkle zero-hash defaults from `lib/merkleTree.ts` (kept in hex
 *  to match Solidity `_zeros(d)`) flow through the WebView path fine but
 *  panic the native witness calculator with `ParseBigIntError`. */
const HEX_BIGINT = /^0x[0-9a-fA-F]+$/;

function hasHexBigInt(value: unknown): boolean {
  if (typeof value === 'string') return HEX_BIGINT.test(value);
  if (Array.isArray(value)) return value.some(hasHexBigInt);
  if (value && typeof value === 'object') {
    return Object.values(value as Record<string, unknown>).some(hasHexBigInt);
  }
  return false;
}

function deepDecimal(value: unknown): unknown {
  if (typeof value === 'string') {
    return HEX_BIGINT.test(value) ? BigInt(value).toString(10) : value;
  }
  if (Array.isArray(value)) return value.map(deepDecimal);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = deepDecimal(v);
    }
    return out;
  }
  return value;
}

/** Recursively rewrite hex BigInt strings to base-10. Returns the original
 *  reference unchanged when the tree is already all-decimal — once callers
 *  emit decimal at source, the steady-state allocation is zero. */
function decimalize(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  return hasHexBigInt(inputs) ? (deepDecimal(inputs) as Record<string, unknown>) : inputs;
}

/** circom-prover's `json_to_hashmap` (rustwitness path) only ingests
 *  values whose top-level JSON form is an Array of strings — single
 *  strings are silently dropped, leaving the witness with missing
 *  inputs and the proof with all-zero public outputs. snarkjs is
 *  permissive and auto-wraps singletons; we replicate that here so
 *  callers can keep using the same `Record<string, string | string[]>`
 *  shape on both backends. */
function wrapSingletons(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(inputs)) {
    out[k] = Array.isArray(v) ? v : [v];
  }
  return out;
}

function normalizeInputs(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  return wrapSingletons(decimalize(inputs));
}

/** Shape matching `snarkjs.groth16.fullProve` so `formatProofForSolidity`
 *  and other downstream helpers keep working unchanged when this path is
 *  picked over the WebView one. */
export type SnarkjsLikeProofResult = {
  proof: {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
  };
  publicSignals: string[];
  elapsedMs: number;
};

/** Append-only log of every native prove call's outputs. Lives in the
 *  app's documents dir so it survives Metro reloads but is wiped on app
 *  uninstall. Disabled in production builds — the log retains debug
 *  metadata only (proving inputs include witness `secret`/`salt`, so we
 *  never persist them; only public outputs and proof points are kept).
 *
 *  Writes are queued so callers can `void appendProveLog(...)` on the
 *  hot path without waiting on disk I/O, and use `append: true` so the
 *  per-call cost is O(line) instead of O(fileSize). The byte-cap rotation
 *  re-stats after deletion to avoid acting on stale `info.exists`. */
const PROVE_LOG_FILENAME = 'native_prover.log';
const PROVE_LOG_MAX_BYTES = 4 * 1024 * 1024;

function getProveLogPath(): string | null {
  const dir = FileSystem.documentDirectory;
  return dir ? `${dir}${PROVE_LOG_FILENAME}` : null;
}

/** Drop fields that may contain witness secrets (`secret`, `salt`,
 *  private claim/note material). Public outputs and proof points are
 *  safe — they're the same values the relayer sees on submit. */
function redactInputsForLog(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  const SENSITIVE = new Set([
    'secret', 'salt', 'noteSecret', 'noteSalt',
    'pathSecret', 'sk', 'privateKey',
  ]);
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(inputs)) {
    out[k] = SENSITIVE.has(k) ? '[redacted]' : '[present]';
  }
  return out;
}

let proveLogChain: Promise<void> = Promise.resolve();
function appendProveLog(record: Record<string, unknown>): void {
  if (!__DEV__) return;
  const path = getProveLogPath();
  if (!path) return;
  const line = JSON.stringify({ ts: new Date().toISOString(), ...record }) + '\n';
  proveLogChain = proveLogChain
    .catch(() => {})
    .then(async () => {
      try {
        const info = await FileSystem.getInfoAsync(path);
        if (info.exists && (info as any).size > PROVE_LOG_MAX_BYTES) {
          await FileSystem.deleteAsync(path, { idempotent: true });
        }
        await FileSystem.writeAsStringAsync(path, line, {
          encoding: FileSystem.EncodingType.UTF8,
          append: true,
        } as any);
      } catch {
        // Logging must never break the prove path.
      }
    });
}

/** Runs Groth16 proving for the `authorize` circuit natively. Input is
 *  the same JSON shape snarkjs takes on the WebView side, so callers
 *  don't need to branch. */
export async function generateAuthorizeProof(
  inputs: Record<string, unknown>,
): Promise<SnarkjsLikeProofResult> {
  const zkeyPath = await resolveAuthorizeZkeyPath();
  const normalized = normalizeInputs(inputs);
  const t0 = Date.now();
  // Arkworks is the only proof backend bundled today. Rapidsnark is
  // available as an alternative but not wired in — keep a single path
  // until benchmarks show it's worth the extra binary size.
  let res: ReturnType<typeof generateCircomProof>;
  try {
    res = generateCircomProof(zkeyPath, JSON.stringify(normalized), ProofLib.Arkworks);
  } catch (e: any) {
    appendProveLog({
      kind: 'authorize.error',
      zkeyPath,
      inputKeys: redactInputsForLog(normalized),
      error: { name: e?.name, message: e?.message, str: String(e) },
    });
    throw e;
  }
  const elapsedMs = Date.now() - t0;
  appendProveLog({
    kind: 'authorize.ok',
    elapsedMs,
    zkeyPath,
    inputKeys: redactInputsForLog(normalized),
    publicSignals: res.inputs,
    proof: res.proof,
  });
  // mopro returns G1/G2 points as {x,y,z} / {x:[],y:[],z:[]}. snarkjs
  // returns pi_a / pi_b / pi_c as flat arrays. Convert here so callers
  // can keep using `formatProofForSolidity` without branching.
  return {
    proof: {
      pi_a: [res.proof.a.x, res.proof.a.y, res.proof.a.z],
      pi_b: [
        [res.proof.b.x[0], res.proof.b.x[1]],
        [res.proof.b.y[0], res.proof.b.y[1]],
        [res.proof.b.z[0], res.proof.b.z[1]],
      ],
      pi_c: [res.proof.c.x, res.proof.c.y, res.proof.c.z],
    },
    publicSignals: res.inputs,
    elapsedMs,
  };
}
