/**
 * NativeProverService — thin wrapper over mopro-ffi's `generateCircomProof`
 * for the authorize circuit.
 *
 * Why this exists: the WebView path (ZKBridgeService + snarkjs inside
 * HiddenWebView) spikes the WebKit process CPU for ~1–2s per proof, and
 * on the iOS Simulator this starves the shared dispatch queue so that
 * every HTTP call dispatched right after the proof aborts at its
 * deadline — see the `OrderService` diagnostic logs in PR #408 and the
 * abort chain in #401/#404/#407. Running the prover as native code
 * removes the burst (arkworks/groth16 runs on a native thread) and with
 * it the NSURLSession stall.
 *
 * Scope: authorize only. Deposit/claim/cancel still route through the
 * WebView until this path is validated end-to-end; the router lives in
 * `ZKBridgeService.generateProof`.
 */
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
// `mopro-ffi` is a local file: dependency generated by `mobile/native-prover`.
// The generated TS calls into the Turbo Module on first import, which
// registers the Rust crate with Hermes. Keep this import module-scoped so
// that registration happens once per JS runtime (Metro hot-reloads will
// dedupe via the rustInstalled flag inside the package).
import { generateCircomProof, ProofLib } from 'mopro-ffi';

// `set_circom_circuits!` in `mobile/native-prover/src/lib.rs` keys the
// witness function on this exact basename — expo-asset's hashed filename
// fails the `Path::file_name()` match, so we copy under the original.
const ZKEY_FILENAME = 'authorize_final.zkey';

let cachedZkeyPath: string | null = null;

/** Resolves the bundled zkey to a plain filesystem path the Rust side can
 *  `std::fs::File::open`. The FFI path must not have a `file://` prefix —
 *  Rust's File::open rejects URI-form paths. */
async function resolveAuthorizeZkeyPath(): Promise<string> {
  if (cachedZkeyPath) return cachedZkeyPath;
  const asset = Asset.fromModule(require('../../assets/zk-native/authorize_final.zkey'));
  await asset.downloadAsync();
  const uri = asset.localUri || asset.uri;
  if (!uri) throw new Error(`${ZKEY_FILENAME} asset could not be resolved`);
  // expo's `documentDirectory` is `null` until the FS module finishes
  // initializing; bail with a clear message rather than concatenating a
  // literal `nullauthorize_final.zkey` path that mopro will then reject.
  const docDir = FileSystem.documentDirectory;
  if (!docDir) throw new Error('expo-file-system documentDirectory unavailable');
  // expo-file-system on Android requires URI-form paths (with the
  // `file://` scheme) for `copyAsync`; iOS accepts both. Strip the
  // scheme only when the resulting plain path crosses the FFI to Rust,
  // which uses `std::fs::File::open` and rejects URI-form input.
  const destPath = `${docDir}${ZKEY_FILENAME}`;
  const destInfo = await FileSystem.getInfoAsync(destPath);
  if (!destInfo.exists) {
    await FileSystem.copyAsync({ from: uri, to: destPath });
  }
  cachedZkeyPath = destPath.replace(/^file:\/\//, '');
  return cachedZkeyPath;
}

/** circom-prover (the arkworks backend mopro uses) only parses decimal
 *  BigInt strings. snarkjs is lenient and accepts hex (`0x…`), which is
 *  why merkle zero-hash defaults from `lib/merkleTree.ts` (kept in hex
 *  to match Solidity `_zeros(d)`) flow through the WebView path fine but
 *  panic the native witness calculator with `ParseBigIntError`. */
const HEX_BIGINT = /^0x[0-9a-fA-F]+$/;

function hasHexBigInt(value: unknown): boolean {
  if (typeof value === 'string') return HEX_BIGINT.test(value);
  if (Array.isArray(value)) return value.some(hasHexBigInt);
  if (value && typeof value === 'object') {
    return Object.values(value as Record<string, unknown>).some(hasHexBigInt);
  }
  return false;
}

function deepDecimal(value: unknown): unknown {
  if (typeof value === 'string') {
    return HEX_BIGINT.test(value) ? BigInt(value).toString(10) : value;
  }
  if (Array.isArray(value)) return value.map(deepDecimal);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = deepDecimal(v);
    }
    return out;
  }
  return value;
}

/** Recursively rewrite hex BigInt strings to base-10. Returns the original
 *  reference unchanged when the tree is already all-decimal — once callers
 *  emit decimal at source, the steady-state allocation is zero. */
function decimalize(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  return hasHexBigInt(inputs) ? (deepDecimal(inputs) as Record<string, unknown>) : inputs;
}

/** circom-prover's `json_to_hashmap` (rustwitness path) only ingests
 *  values whose top-level JSON form is an Array of strings — single
 *  strings are silently dropped, leaving the witness with missing
 *  inputs and the proof with all-zero public outputs. snarkjs is
 *  permissive and auto-wraps singletons; we replicate that here so
 *  callers can keep using the same `Record<string, string | string[]>`
 *  shape on both backends. */
function wrapSingletons(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(inputs)) {
    out[k] = Array.isArray(v) ? v : [v];
  }
  return out;
}

function normalizeInputs(
  inputs: Record<string, unknown>,
): Record<string, unknown> {
  return wrapSingletons(decimalize(inputs));
}

/** Shape matching `snarkjs.groth16.fullProve` so `formatProofForSolidity`
 *  and other downstream helpers keep working unchanged when this path is
 *  picked over the WebView one. */
export type SnarkjsLikeProofResult = {
  proof: {
    pi_a: string[];
    pi_b: string[][];
    pi_c: string[];
  };
  publicSignals: string[];
  elapsedMs: number;
};

/** Append-only log of every native prove call. Dev-only — secrets like
 *  `note.secret`, `salt`, `claimSecrets` and the EdDSA signature live in
 *  the circuit `inputs` object, so this would persist witness material
 *  to disk in production. Diagnostic value is "did the proof go through
 *  and what were the public signals", which is captured by `kind`,
 *  `elapsedMs`, `publicSignals` and a redacted input shape — not by
 *  logging the raw witness. */
const PROVE_LOG_FILENAME = 'native_prover.log';
const PROVE_LOG_MAX_BYTES = 1 * 1024 * 1024; // 1 MiB; entries are small
const SENSITIVE_INPUT_KEYS = new Set([
  'secret', 'salt', 'newSalt',
  'sigS', 'sigR8x', 'sigR8y',
  'claimSecrets',
]);

function redactInputs(inputs: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(inputs)) {
    out[k] = SENSITIVE_INPUT_KEYS.has(k) ? '<redacted>' : v;
  }
  return out;
}

// Serialise writes through a single promise chain so concurrent prove
// calls can't interleave a read-modify-write race that drops entries
// or corrupts the file.
let proveLogQueue: Promise<void> = Promise.resolve();

async function appendProveLog(record: Record<string, unknown>): Promise<void> {
  // Gate behind __DEV__ so production builds never touch disk on a
  // prove call. The variable is statically replaced by Metro at bundle
  // time, so the file-system code below tree-shakes out of release.
  if (!__DEV__) return;
  // Resolve the path lazily — `FileSystem.documentDirectory` is `null`
  // for a brief window before expo-file-system finishes its first
  // initialization (early prove call from a cold start).
  const docDir = FileSystem.documentDirectory;
  if (!docDir) return;
  const path = `${docDir}${PROVE_LOG_FILENAME}`;
  proveLogQueue = proveLogQueue.then(async () => {
    try {
      const line = JSON.stringify({ ts: new Date().toISOString(), ...record }) + '\n';
      const info = await FileSystem.getInfoAsync(path);
      const overCap = info.exists && (info as any).size > PROVE_LOG_MAX_BYTES;
      if (overCap) {
        // Overwrite for rotation. The previous version deleted then read,
        // which raced (`readAsStringAsync` after `deleteAsync` would throw
        // and the catch dropped the new record).
        await FileSystem.writeAsStringAsync(path, line);
        return;
      }
      const existing = info.exists ? await FileSystem.readAsStringAsync(path) : '';
      await FileSystem.writeAsStringAsync(path, existing + line);
    } catch {
      // Logging must never break the prove path.
    }
  });
}

/** Runs Groth16 proving for the `authorize` circuit natively. Input is
 *  the same JSON shape snarkjs takes on the WebView side, so callers
 *  don't need to branch. */
export async function generateAuthorizeProof(
  inputs: Record<string, unknown>,
): Promise<SnarkjsLikeProofResult> {
  const zkeyPath = await resolveAuthorizeZkeyPath();
  const normalized = normalizeInputs(inputs);
  const t0 = Date.now();
  // Arkworks is the only proof backend bundled today. Rapidsnark is
  // available as an alternative but not wired in — keep a single path
  // until benchmarks show it's worth the extra binary size.
  let res: ReturnType<typeof generateCircomProof>;
  try {
    res = generateCircomProof(zkeyPath, JSON.stringify(normalized), ProofLib.Arkworks);
  } catch (e: any) {
    void appendProveLog({
      kind: 'authorize.error',
      zkeyPath,
      inputs: redactInputs(normalized),
      error: { name: e?.name, message: e?.message, str: String(e) },
    });
    throw e;
  }
  const elapsedMs = Date.now() - t0;
  void appendProveLog({
    kind: 'authorize.ok',
    elapsedMs,
    zkeyPath,
    inputs: redactInputs(normalized),
    publicSignals: res.inputs,
  });
  // mopro returns G1/G2 points as {x,y,z} / {x:[],y:[],z:[]}. snarkjs
  // returns pi_a / pi_b / pi_c as flat arrays. Convert here so callers
  // can keep using `formatProofForSolidity` without branching.
  return {
    proof: {
      pi_a: [res.proof.a.x, res.proof.a.y, res.proof.a.z],
      pi_b: [
        [res.proof.b.x[0], res.proof.b.x[1]],
        [res.proof.b.y[0], res.proof.b.y[1]],
        [res.proof.b.z[0], res.proof.b.z[1]],
      ],
      pi_c: [res.proof.c.x, res.proof.c.y, res.proof.c.z],
    },
    publicSignals: res.inputs,
    elapsedMs,
  };
}
