// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {BatchAuthorizeVerifier64} from "../src/zk/BatchAuthorizeVerifier_64.sol";
import {BatchAuthorizeVerifier128} from "../src/zk/BatchAuthorizeVerifier_128.sol";
import {IBatchAuthorizeVerifier} from "../src/zk/IBatchAuthorizeVerifier.sol";

interface IAuthVerifier {
    function verifyProof(uint256[2] calldata, uint256[2][2] calldata, uint256[2] calldata, uint256[15] calldata)
        external
        view
        returns (bool);
}

/// @notice Real-proof tests for the tier-64 / tier-128 BatchAuthorizeVerifier
///         contracts. Fixtures are generated by
///         `circuits/test/gen-batch-fixtures.cjs` (real snarkjs proofs against
///         each tier's zkey). Run under the via-ir profile:
///           FOUNDRY_PROFILE=batch-verifier forge test --match-contract BatchAuthorizeVerifierReal
///         The Sepolia-fork oracle tests additionally need an RPC and run
///         only when SEPOLIA_RPC_URL is set.
contract BatchAuthorizeVerifierRealTest is Test {
    struct Proof {
        uint256[2] pA;
        uint256[2][2] pB;
        uint256[2] pC;
        uint256[15] pub;
    }

    // Regular per-tier verifiers deployed on Sepolia (deployments/11155111.json).
    address constant SEPOLIA_AUTH_64 = 0x3186864eE4952D2fdd2889CEd675794D762B8226;
    address constant SEPOLIA_AUTH_128 = 0xFC955Bd5Dc10aa3216b44445e8B839Eb2abCd2d4;
    // BN254 base field modulus.
    uint256 constant Q_MOD = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    function _parse(string memory json, string memory key) internal pure returns (Proof memory p) {
        uint256[] memory pA = vm.parseJsonUintArray(json, string.concat(key, ".pA"));
        uint256[] memory pB0 = vm.parseJsonUintArray(json, string.concat(key, ".pB[0]"));
        uint256[] memory pB1 = vm.parseJsonUintArray(json, string.concat(key, ".pB[1]"));
        uint256[] memory pC = vm.parseJsonUintArray(json, string.concat(key, ".pC"));
        uint256[] memory pub = vm.parseJsonUintArray(json, string.concat(key, ".pub"));
        p.pA = [pA[0], pA[1]];
        p.pB = [[pB0[0], pB0[1]], [pB1[0], pB1[1]]];
        p.pC = [pC[0], pC[1]];
        for (uint256 i = 0; i < 15; i++) p.pub[i] = pub[i];
    }

    /// @dev Reads + parses the fixture file once, returning both proofs.
    function _loadBoth(string memory fixture) internal view returns (Proof memory p1, Proof memory p2) {
        string memory json = vm.readFile(string.concat(vm.projectRoot(), "/test/fixtures/", fixture));
        p1 = _parse(json, ".proof1");
        p2 = _parse(json, ".proof2");
    }

    function _verifyBatch(IBatchAuthorizeVerifier v, Proof memory a, Proof memory b) internal view returns (bool) {
        return v.verifyBatchProof(a.pA, a.pB, a.pC, a.pub, b.pA, b.pB, b.pC, b.pub);
    }

    // ── acceptance: each tier's real proof pair verifies (proves the vkey) ──

    function test_batch64_realProofPair_accepts() public {
        (Proof memory p1, Proof memory p2) = _loadBoth("batch_authorize_64.json");
        assertTrue(_verifyBatch(new BatchAuthorizeVerifier64(), p1, p2), "valid tier-64 pair must verify");
    }

    function test_batch128_realProofPair_accepts() public {
        (Proof memory p1, Proof memory p2) = _loadBoth("batch_authorize_128.json");
        assertTrue(_verifyBatch(new BatchAuthorizeVerifier128(), p1, p2), "valid tier-128 pair must verify");
    }

    // ── rejection: the batch assembly is tier-agnostic, so one tamper case
    //    per tier is enough to exercise the reject path against each vkey ──

    function test_batch64_tamperedProof_rejects() public {
        (Proof memory p1, Proof memory p2) = _loadBoth("batch_authorize_64.json");
        p1.pub[2] ^= 1; // flip a bit in proof-1's nullifier signal
        assertFalse(_verifyBatch(new BatchAuthorizeVerifier64(), p1, p2), "tampered public signal must fail");
    }

    function test_batch128_tamperedProof_rejects() public {
        (Proof memory p1, Proof memory p2) = _loadBoth("batch_authorize_128.json");
        p2.pA[0] ^= 1; // corrupt proof-2's A point
        assertFalse(_verifyBatch(new BatchAuthorizeVerifier128(), p1, p2), "corrupted A must fail");
    }

    /// @dev Regression for the pA1.y malleability fix: a valid proof whose A.y
    ///      is shifted by +q_mod (same point mod q) must be rejected by the
    ///      explicit `pA1.y < q_mod` guard. Without the guard this aliased
    ///      encoding would verify identically to the original.
    function test_batch64_malleableA1y_rejects() public {
        (Proof memory p1, Proof memory p2) = _loadBoth("batch_authorize_64.json");
        p1.pA[1] = p1.pA[1] + Q_MOD; // < 2^256 (coord < q ≈ 2^254), so no overflow
        assertFalse(_verifyBatch(new BatchAuthorizeVerifier64(), p1, p2), "A1.y >= q_mod must be rejected");
    }

    // ── Sepolia-fork oracle: the batch vkey matches the LIVE regular verifier ──
    // The batch verifier shares its vkey with AuthorizeVerifier_<tier>.sol. We
    // assert the real proof verifies against BOTH our local batch verifier and
    // the regular verifier already deployed on Sepolia — proving the embedded
    // vkey matches the live deployment (not just the repo source).

    function _forkOracle(IBatchAuthorizeVerifier v, address liveRegular, string memory fixture) internal {
        (Proof memory p1, Proof memory p2) = _loadBoth(fixture);
        assertTrue(
            IAuthVerifier(liveRegular).verifyProof(p1.pA, p1.pB, p1.pC, p1.pub),
            "live regular verifier must accept the fixture proof"
        );
        assertTrue(_verifyBatch(v, p1, p2), "batch verifier must accept the same real pair");
    }

    function test_fork_batch64_vkeyMatchesLiveRegularVerifier() public {
        string memory rpc = vm.envOr("SEPOLIA_RPC_URL", string(""));
        vm.skip(bytes(rpc).length == 0);
        vm.createSelectFork(rpc);
        _forkOracle(new BatchAuthorizeVerifier64(), SEPOLIA_AUTH_64, "batch_authorize_64.json");
    }

    function test_fork_batch128_vkeyMatchesLiveRegularVerifier() public {
        string memory rpc = vm.envOr("SEPOLIA_RPC_URL", string(""));
        vm.skip(bytes(rpc).length == 0);
        vm.createSelectFork(rpc);
        _forkOracle(new BatchAuthorizeVerifier128(), SEPOLIA_AUTH_128, "batch_authorize_128.json");
    }
}
