"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ethers } from "ethers";
import { useWallet, shortAddr } from "@zkscatter/sdk/react";
import { PRIVATE_SETTLEMENT_ABI } from "@zkscatter/sdk";
import { decodeClaimPackage, type ClaimPackage } from "@zkscatter/sdk/notes";
import { computeClaimNullifier, toBytes32Hex } from "@zkscatter/sdk/zk";
import { RelayerClient } from "@zkscatter/sdk/relayer";
import {
  addClaimInboxEntry,
  markClaimInboxEntryClaimed,
} from "@zkscatter/sdk/storage";
import { buildExplorerTxUrl } from "@zkscatter/sdk/util";
import { DEMO_NETWORK } from "../lib/network";
import { formatLocalStampSec } from "../lib/format";
import { submitClaim } from "../lib/claimSubmit";
import { useIdentityStatus } from "../lib/identity";
import { useFolder } from "../lib/folder";

/** Pro counterpart of Pay's /claim. Port of `apps/pay/app/claim/page.tsx`
 *  with Pro's lib imports — same claim pipeline (`submitClaim` covers
 *  on-chain claims-group probe → ZK proof → gasless dispatch → self-pay
 *  fallback) so a claim package generated by either app round-trips
 *  identically: paste the URL → decode → claim. Previously Pro's
 *  `/claim` was a landing-only summary that left the recipient with
 *  no submit affordance — see PR #857 for the per-relayer leaderboard
 *  fairness work that shipped alongside this. */
export default function ClaimPage() {
  return (
    <Suspense
      fallback={
        <div className="mx-auto max-w-md py-10 text-center text-sm text-[var(--color-text-muted)]">
          Loading claim…
        </div>
      }
    >
      <ClaimInner />
    </Suspense>
  );
}

interface ParsedClaim {
  pkg: ClaimPackage;
  amountRaw: bigint;
  releaseTimeUnix: number;
  recipientLower: string;
}

function parseHashToClaim(hash: string | null): ParsedClaim | null {
  if (!hash) return null;
  // Strip the leading `#`, then keep only the first fragment segment.
  // Some routers double-push the hash on client-side nav, producing
  // `#FRAG#FRAG`; base64url has no `#`, so anything after the second
  // can't be part of the payload. (Same defense Pay's /claim ships.)
  const firstSegment = hash.replace(/^#/, "").split("#", 1)[0];
  if (!firstSegment) return null;
  const pkg = decodeClaimPackage(firstSegment);
  return {
    pkg,
    amountRaw: BigInt(pkg.amount),
    releaseTimeUnix: Number(BigInt(pkg.releaseTime)),
    recipientLower: pkg.recipient.toLowerCase(),
  };
}

type Phase =
  | { kind: "idle" }
  | { kind: "validating" }
  | { kind: "proving" }
  | { kind: "submitting" }
  | { kind: "done"; txHash: string }
  | { kind: "error"; message: string };

function ClaimInner() {
  const searchParams = useSearchParams();
  const link = searchParams?.get("id") ?? "";
  const { account, chainId: walletChainId, signer, readProvider, connect, connectError } = useWallet();
  const folder = useFolder();
  const [parsed, setParsed] = useState<ParsedClaim | null>(null);
  const [parseError, setParseError] = useState<string | null>(null);
  const [phase, setPhase] = useState<Phase>({ kind: "idle" });
  const [forceSelfPay, setForceSelfPay] = useState(false);
  const [savedInboxId, setSavedInboxId] = useState<string | null>(null);
  const [preSaveState, setPreSaveState] = useState<
    "idle" | "saving" | "saved" | "duplicate"
  >("idle");
  // Relayer reachability probe — drives the gasless button's disabled
  // state so the recipient doesn't burn a proof generation just to hit
  // a connection refused.
  const [relayerUp, setRelayerUp] = useState<boolean | null>(null);
  useEffect(() => {
    const url = parsed?.pkg.relayerUrl;
    if (!url) {
      setRelayerUp(null);
      return;
    }
    const ctrl = new AbortController();
    new RelayerClient(url)
      .getInfo(ctrl.signal)
      .then(() => setRelayerUp(true))
      .catch(() => setRelayerUp(false));
    return () => ctrl.abort();
  }, [parsed?.pkg.relayerUrl]);

  // EOA claims require the connecting wallet (= recipient) to be
  // zk-X509 verified — same gate Pay enforces.
  const { state: claimerIdentity } = useIdentityStatus();
  const recipientUnverified =
    !!account &&
    (claimerIdentity.kind === "unverified" ||
      claimerIdentity.kind === "expired" ||
      claimerIdentity.kind === "error");

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      setParsed(parseHashToClaim(window.location.hash));
    } catch (err) {
      setParseError(err instanceof Error ? err.message : String(err));
    }
  }, []);

  const cfg = DEMO_NETWORK;
  const explorerTxUrl = useMemo<((hash: string) => string) | null>(() => {
    const base = cfg.explorerBase;
    if (!base) return null;
    if (buildExplorerTxUrl(base, "x") === null) return null;
    return (txHash: string) => buildExplorerTxUrl(base, txHash) ?? base;
  }, [cfg.explorerBase]);
  const isAvailable = parsed
    ? Math.floor(Date.now() / 1000) >= parsed.releaseTimeUnix
    : undefined;
  // Probe whether the nullifier was already spent on-chain so a
  // recipient who clicks the link twice sees "Already claimed" instead
  // of being invited to burn another proof generation.
  const [alreadyClaimed, setAlreadyClaimed] = useState<boolean | null>(null);
  useEffect(() => {
    if (!parsed || !readProvider) {
      setAlreadyClaimed(null);
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        const nullifier = await computeClaimNullifier(
          BigInt(parsed.pkg.secret),
          BigInt(parsed.pkg.leafIndex),
        );
        const settlement = new ethers.Contract(
          parsed.pkg.settlementAddress,
          PRIVATE_SETTLEMENT_ABI,
          readProvider,
        );
        const spent = (await settlement.claimNullifiers(
          toBytes32Hex(nullifier),
        )) as boolean;
        if (!cancelled) setAlreadyClaimed(spent);
      } catch {
        if (!cancelled) setAlreadyClaimed(null);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [parsed, readProvider]);
  const wrongAppChain = parsed && parsed.pkg.chainId !== cfg.chainId;
  const wrongWalletChain =
    !!parsed && walletChainId !== null && walletChainId !== parsed.pkg.chainId;
  const wrongRecipient =
    !!parsed &&
    !!account &&
    account.toLowerCase() !== parsed.recipientLower;
  const gasless = !!parsed?.pkg.relayerUrl && !forceSelfPay;

  async function saveToInbox() {
    if (!parsed || !folder.ready || preSaveState !== "idle") return;
    setPreSaveState("saving");
    try {
      const rawInput =
        typeof window !== "undefined" ? window.location.href : "";
      const { isNew } = await addClaimInboxEntry({
        rawInput,
        pkg: parsed.pkg,
      });
      setPreSaveState(isNew ? "saved" : "duplicate");
    } catch (err) {
      console.warn("[Pro] pre-claim save failed", err);
      setPreSaveState("idle");
    }
  }

  async function doClaim() {
    if (!parsed) return;
    const claimSigner = signer ?? undefined;
    if (!gasless && !claimSigner) return;
    try {
      const { txHash } = await submitClaim({
        pkg: parsed.pkg,
        readProvider,
        signer: claimSigner,
        forceSelfPay,
        onPhase: (kind) => setPhase({ kind }),
      });
      setPhase({ kind: "done", txHash });
      // Best-effort save to the local inbox so the recipient can see
      // the claim again next session. A save failure must not surface
      // as a claim error — the on-chain tx already succeeded.
      if (folder.ready) {
        try {
          const rawInput =
            typeof window !== "undefined" ? window.location.href : "";
          const { entry } = await addClaimInboxEntry({
            rawInput,
            pkg: parsed.pkg,
          });
          await markClaimInboxEntryClaimed(entry.id, txHash);
          setSavedInboxId(entry.id);
        } catch (saveErr) {
          console.warn("[Pro] save-to-inbox after claim failed", saveErr);
        }
      }
    } catch (err) {
      console.error("[Pro] claim failed", err);
      setPhase({
        kind: "error",
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  if (parseError) {
    return (
      <div className="mx-auto max-w-md py-10 text-center text-sm text-[var(--color-warning)]">
        Could not read this claim link: {parseError}
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-md py-10">
      <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-8 shadow-sm">
        {parsed?.pkg.senderLabel && (
          <div className="mb-5 flex items-center justify-center gap-2 text-xs">
            <span className="text-[var(--color-text-subtle)]">From</span>
            <span className="font-medium">{parsed.pkg.senderLabel}</span>
          </div>
        )}

        <div className="mb-2 text-center text-xs uppercase tracking-wide text-[var(--color-text-subtle)]">
          {parsed?.pkg.runLabel ?? "Private trade share"}
        </div>
        <div className="text-center text-3xl font-semibold">
          {parsed
            ? ethers.formatUnits(parsed.amountRaw, parsed.pkg.tokenDecimals)
            : "—"}{" "}
          <span className="text-base font-normal text-[var(--color-text-muted)]">
            {parsed?.pkg.tokenSymbol ?? ""}
          </span>
        </div>
        <div className="mt-1 text-center text-sm text-[var(--color-text-muted)]">
          You only see your amount.
        </div>

        <div className="mx-auto mt-5 inline-block w-full rounded-md bg-[var(--color-primary-soft)] p-2 text-center text-xs text-[var(--color-primary)]">
          🔒 Funds can only go to{" "}
          {parsed ? (
            <span className="break-all font-mono">{parsed.pkg.recipient}</span>
          ) : (
            "you"
          )}.
          <span className="mt-0.5 block text-[10px] text-[var(--color-text-muted)]">
            Claim anytime — no expiry.
          </span>
        </div>

        <div className="mt-4 rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] p-3 text-xs">
          {parsed === null ? (
            <span className="text-[var(--color-warning)]">
              Open the original message you received and click the link from
              there — this page needs the secret encoded in the URL.
            </span>
          ) : alreadyClaimed === true && phase.kind !== "done" ? (
            <span className="text-[var(--color-text-muted)]">
              ✓ Already claimed — this link&apos;s slot was spent earlier.
            </span>
          ) : isAvailable === undefined ? (
            <span className="text-[var(--color-text-muted)]">Checking availability…</span>
          ) : isAvailable ? (
            <span className="text-[var(--color-success)]">
              ✓ Available to claim now (
              {formatLocalStampSec(parsed.releaseTimeUnix)})
            </span>
          ) : (
            <span className="text-[var(--color-warning)]">
              ⏳ Available from {formatLocalStampSec(parsed.releaseTimeUnix)}
            </span>
          )}
        </div>

        <div className="mt-5 space-y-3">
          {phase.kind === "done" ? (
            <div className="rounded-md border border-[var(--color-success)] bg-[var(--color-success-soft)] p-3 text-center text-xs text-[var(--color-success)]">
              <div className="mb-1 font-semibold">✓ Claimed</div>
              {explorerTxUrl ? (
                <a
                  href={explorerTxUrl(phase.txHash)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-mono underline-offset-2 hover:underline"
                >
                  {shortAddr(phase.txHash)} ↗
                </a>
              ) : (
                <div className="font-mono">{shortAddr(phase.txHash)}</div>
              )}
              <div className="mt-2 text-[10px] text-[var(--color-text-muted)]">
                {/* `parsed` is guaranteed here — the claim flow can't
                    reach `done` without it, since doClaim() bails on
                    `!parsed`. */}
                Tokens are on-chain at {shortAddr(parsed!.pkg.recipient)}.
                Refresh your wallet if the balance hasn&apos;t updated yet.
              </div>
              {savedInboxId && (
                <div className="mt-2 text-[10px]">
                  Saved to your{" "}
                  <a
                    href="/claims"
                    className="font-medium underline-offset-2 hover:underline"
                  >
                    Claims inbox
                  </a>
                  .
                </div>
              )}
            </div>
          ) : (() => {
              if (parsed && wrongAppChain) {
                return (
                  <div className="rounded-md border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-3 text-center text-xs text-[var(--color-warning)]">
                    <strong className="mb-0.5 block">Wrong Pro deployment</strong>
                    This Pro build targets chain {cfg.chainId}, but the link
                    is for chain {parsed.pkg.chainId}. Open it on the right
                    deployment to claim.
                  </div>
                );
              }
              const needWallet = !gasless;
              const busy =
                phase.kind === "validating" ||
                phase.kind === "proving" ||
                phase.kind === "submitting";
              if (needWallet && !account) {
                return (
                  <>
                    <button
                      onClick={() => void connect()}
                      className="w-full rounded-lg bg-[var(--color-primary)] py-3 text-sm font-medium text-white hover:bg-[var(--color-primary-hover)]"
                    >
                      Connect wallet to claim
                    </button>
                    {connectError && (
                      <div className="text-center text-xs text-[var(--color-danger)]">
                        {connectError === "no-wallet"
                          ? "Install MetaMask to continue."
                          : connectError}
                      </div>
                    )}
                  </>
                );
              }
              return (
                <>
                  {needWallet && account && (
                    <div className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] p-2 text-center text-xs text-[var(--color-text-muted)]">
                      Connected: <span className="font-mono">{shortAddr(account)}</span>
                    </div>
                  )}
                  {needWallet && wrongWalletChain && (
                    <div className="rounded-md border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-2 text-center text-xs text-[var(--color-warning)]">
                      Switch your wallet to chain {parsed!.pkg.chainId} — submitting on the wrong network would target the wrong contract at the same address.
                    </div>
                  )}
                  {needWallet && wrongRecipient && (
                    <div className="rounded-md border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-2 text-center text-xs text-[var(--color-warning)]">
                      This claim is bound to {shortAddr(parsed!.pkg.recipient)} —
                      switch wallets to claim.
                    </div>
                  )}
                  {recipientUnverified && (
                    <div className="rounded-md border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-2 text-center text-xs text-[var(--color-warning)]">
                      Your wallet isn&apos;t zk-X509 verified yet. Recipients
                      must verify before claiming.{" "}
                      <a
                        href="/identity"
                        className="font-medium underline underline-offset-2"
                      >
                        Register with zk-X509 →
                      </a>
                    </div>
                  )}
                  <button
                    onClick={() => void doClaim()}
                    disabled={
                      !parsed ||
                      !isAvailable ||
                      (needWallet && wrongWalletChain) ||
                      (needWallet && wrongRecipient) ||
                      recipientUnverified ||
                      busy ||
                      (gasless && relayerUp === false) ||
                      alreadyClaimed === true
                    }
                    title={
                      alreadyClaimed === true
                        ? "This claim slot was already spent on-chain."
                        : gasless && relayerUp === false
                        ? "Operator's relayer is unreachable — use the wallet button below to claim directly."
                        : undefined
                    }
                    className="w-full rounded-lg bg-[var(--color-primary)] py-3 text-sm font-medium text-white hover:bg-[var(--color-primary-hover)] disabled:opacity-50"
                  >
                    {phase.kind === "validating" && "Verifying on-chain claim group…"}
                    {phase.kind === "proving" && "Generating ZK claim proof…"}
                    {phase.kind === "submitting" &&
                      (gasless ? "Dispatching via relayer…" : "Submitting…")}
                    {phase.kind === "idle" &&
                      (alreadyClaimed === true
                        ? "Already claimed"
                        : gasless
                          ? relayerUp === false
                            ? "Relayer offline"
                            : "Claim — gasless"
                          : "Claim")}
                    {phase.kind === "error" && "Try again"}
                  </button>
                  {phase.kind === "error" && (
                    <div className="rounded-md border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-2 text-xs text-[var(--color-warning)]">
                      <strong className="mb-0.5 block">Claim failed</strong>
                      {phase.message}
                    </div>
                  )}
                  {gasless && (phase.kind === "idle" || phase.kind === "error") && (
                    <button
                      onClick={() => {
                        setForceSelfPay(true);
                        setPhase({ kind: "idle" });
                      }}
                      title="Bypass the operator's relayer and submit the claim tx from your own wallet (you pay the gas)."
                      className="w-full rounded-md border border-[var(--color-border-strong)] py-2 text-xs hover:bg-[var(--color-primary-soft)]"
                    >
                      Submit with my wallet instead (you pay gas)
                    </button>
                  )}
                  {folder.ready && (phase.kind === "idle" || phase.kind === "error") && (
                    <button
                      onClick={() => void saveToInbox()}
                      disabled={preSaveState === "saving"}
                      title="Save this link to your Claims inbox so you can re-open it later without re-pasting."
                      className="w-full rounded-md border border-[var(--color-border-strong)] py-2 text-xs hover:bg-[var(--color-primary-soft)] disabled:opacity-50"
                    >
                      {preSaveState === "saving"
                        ? "Saving…"
                        : preSaveState === "saved"
                          ? "✓ Saved to Claims inbox"
                          : preSaveState === "duplicate"
                            ? "Already in your inbox"
                            : "Save to Claims inbox"}
                    </button>
                  )}
                </>
              );
            })()}
        </div>

        <div className="mt-6 flex items-center justify-between border-t border-[var(--color-border)] pt-3 text-xs">
          <span className="text-[var(--color-text-muted)]">
            {gasless
              ? "Gasless — the operator's relayer pays the gas."
              : "Self-pay — gas comes from your wallet."}
          </span>
          <span className="font-mono text-[10px] text-[var(--color-text-subtle)]">{link}</span>
        </div>
      </div>
    </div>
  );
}
