"use client";

import type { ParsedRecipient, RecipientField } from "../types";

interface Props {
  rows: readonly ParsedRecipient[];
  /** Stable React key per row position. Generated by the parent so
   *  removing row #3 doesn't shift focus on row #4. */
  rowKeys: readonly number[];
  columns: readonly RecipientField[];
  maxRows: number;
  /** Token symbol shown next to the amount input (e.g. `USDC`, `ETH`). */
  amountSymbol?: string;
  /** Per-row warning surfaced inline under the row (caller-computed,
   *  e.g. "amount is invalid"). */
  rowWarnings?: Record<number, string>;
  readOnly?: boolean;
  onUpdate(index: number, patch: Partial<ParsedRecipient>): void;
  onRemove(index: number): void;
  onAdd(): void;
}

export function RowEditor({
  rows,
  rowKeys,
  columns,
  maxRows,
  amountSymbol,
  rowWarnings,
  readOnly,
  onUpdate,
  onRemove,
  onAdd,
}: Props) {
  const showName = columns.includes("name");
  const showEmail = columns.includes("email");
  const showReleaseAt = columns.includes("releaseAt");

  return (
    <div className="space-y-1.5">
      {rows.map((r, i) => {
        const warning = rowWarnings?.[i];
        return (
          <div
            key={rowKeys[i] ?? i}
            className="space-y-1.5 rounded-md border border-[var(--color-border)] bg-white p-2 text-xs"
          >
            <div className="grid grid-cols-[auto_1fr_auto] items-center gap-1.5">
              <span className="font-mono text-[var(--color-text-subtle)]">
                #{i + 1}
              </span>
              <input
                type="text"
                placeholder="0x… (empty = self)"
                value={r.address}
                disabled={readOnly}
                onChange={(e) => onUpdate(i, { address: e.target.value })}
                aria-label={`Recipient ${i + 1} address`}
                className="w-full rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 font-mono text-[11px] disabled:opacity-60"
              />
              <button
                type="button"
                onClick={() => onRemove(i)}
                disabled={readOnly || rows.length <= 1}
                aria-label={`Remove recipient ${i + 1}`}
                className="rounded p-0.5 text-[var(--color-text-subtle)] hover:text-[var(--color-danger)] disabled:opacity-30"
              >
                ×
              </button>
            </div>

            {showName && (
              <div className="grid grid-cols-[auto_1fr] items-center gap-1.5 pl-7">
                <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-subtle)]">
                  Name
                </span>
                <input
                  type="text"
                  placeholder="Optional label"
                  value={r.name}
                  disabled={readOnly}
                  onChange={(e) => onUpdate(i, { name: e.target.value })}
                  aria-label={`Recipient ${i + 1} name`}
                  className="w-full rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 disabled:opacity-60"
                />
              </div>
            )}

            <div className="grid grid-cols-[auto_1fr_auto] items-center gap-1.5 pl-7">
              <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-subtle)]">
                Amount
              </span>
              <input
                type="text"
                placeholder="0.0"
                value={r.amount}
                disabled={readOnly}
                onChange={(e) => onUpdate(i, { amount: e.target.value })}
                aria-label={`Recipient ${i + 1} amount`}
                className="w-full rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 text-right font-mono disabled:opacity-60"
              />
              {amountSymbol && (
                <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-subtle)]">
                  {amountSymbol}
                </span>
              )}
            </div>

            {showEmail && (
              <div className="grid grid-cols-[auto_1fr] items-center gap-1.5 pl-7">
                <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-subtle)]">
                  Email
                </span>
                <input
                  type="email"
                  placeholder="optional@example.com"
                  value={r.email ?? ""}
                  disabled={readOnly}
                  onChange={(e) => onUpdate(i, { email: e.target.value })}
                  aria-label={`Recipient ${i + 1} email`}
                  className="w-full rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 disabled:opacity-60"
                />
              </div>
            )}

            {showReleaseAt && (
              <div className="grid grid-cols-[auto_1fr] items-center gap-1.5 pl-7">
                <span className="text-[10px] uppercase tracking-wide text-[var(--color-text-subtle)]">
                  Claim from
                </span>
                <input
                  type="datetime-local"
                  value={r.releaseAt ?? ""}
                  disabled={readOnly}
                  onChange={(e) => onUpdate(i, { releaseAt: e.target.value })}
                  aria-label={`Recipient ${i + 1} claim release time`}
                  className="w-full rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 font-mono disabled:opacity-60"
                />
              </div>
            )}

            {warning && (
              <p className="pl-7 text-[10px] text-[var(--color-danger)]">{warning}</p>
            )}
          </div>
        );
      })}
      {!readOnly && rows.length < maxRows && (
        <button
          type="button"
          onClick={onAdd}
          className="rounded-md border border-dashed border-[var(--color-border-strong)] bg-white px-3 py-1.5 text-[11px] text-[var(--color-text-muted)] hover:border-[var(--color-primary)] hover:text-[var(--color-primary)]"
        >
          + Add recipient
        </button>
      )}
    </div>
  );
}
