"use client";

import type { ParsedRecipient, RecipientField } from "../types";

interface Props {
  rows: readonly ParsedRecipient[];
  /** Stable React key per row position. Generated by the parent so
   *  removing row #3 doesn't shift focus on row #4. */
  rowKeys: readonly number[];
  columns: readonly RecipientField[];
  maxRows: number;
  /** Token symbol shown next to the amount input (e.g. `USDC`, `ETH`). */
  amountSymbol?: string;
  /** Order's projected receive total (display string, comma-allowed).
   *  Combined with `amountDecimals` it enables the per-row Rest
   *  button — fills `(total − sum(other rows))` into the row so the
   *  operator doesn't have to compute the leftover by hand. */
  totalAmount?: string;
  amountDecimals?: number;
  /** Per-row warning surfaced inline under the row (caller-computed,
   *  e.g. "amount is invalid"). */
  rowWarnings?: Record<number, string>;
  readOnly?: boolean;
  onUpdate(index: number, patch: Partial<ParsedRecipient>): void;
  onRemove(index: number): void;
  onAdd(): void;
}

/** Rows mode: a single primary line per recipient with address + amount
 *  inline (the two highest-leverage fields), and a compact second line
 *  for optional metadata when its column is enabled. Originally each
 *  field was its own stacked row which buried the amount three scrolls
 *  down a 128-recipient list. */
export function RowEditor({
  rows,
  rowKeys,
  columns,
  maxRows,
  amountSymbol,
  totalAmount,
  amountDecimals,
  rowWarnings,
  readOnly,
  onUpdate,
  onRemove,
  onAdd,
}: Props) {
  const showName = columns.includes("name");
  const showEmail = columns.includes("email");
  const showReleaseAt = columns.includes("releaseAt");
  const hasMetaLine = showName || showEmail || showReleaseAt;

  // Compute "rest" (total − sum of other rows) for `rowIndex` as a
  // display string. Returns null when totals aren't wired up or the
  // row would receive ≤0 (already over-allocated). Done in display
  // units to round-trip cleanly through the same `parseUnits` the
  // submit path uses.
  const restFor = (rowIndex: number): string | null => {
    if (!totalAmount || amountDecimals === undefined) return null;
    const totalClean = totalAmount.replace(/,/g, "");
    if (!totalClean) return null;
    let totalWei: bigint;
    try {
      totalWei = parseDisplay(totalClean, amountDecimals);
    } catch {
      return null;
    }
    let othersWei = 0n;
    for (let i = 0; i < rows.length; i++) {
      if (i === rowIndex) continue;
      const raw = rows[i]!.amount.replace(/,/g, "");
      if (!raw) continue;
      try {
        othersWei += parseDisplay(raw, amountDecimals);
      } catch {
        // Skip unparseable rows — Rest reflects validated input only.
      }
    }
    if (othersWei >= totalWei) return null;
    return formatDisplay(totalWei - othersWei, amountDecimals);
  };

  return (
    <div className="space-y-1.5">
      {rows.map((r, i) => {
        const warning = rowWarnings?.[i];
        return (
          <div
            key={rowKeys[i] ?? i}
            className="rounded-md border border-[var(--color-border)] bg-white px-2 py-1.5 text-xs"
          >
            {/* Primary line — address + amount on the same row so the
                amount is always visible alongside the recipient. The
                amount input has a fixed pixel width so it doesn't
                shrink at narrow widths; the address takes the rest. */}
            <div className="flex items-center gap-1.5">
              <span className="w-6 shrink-0 font-mono text-[var(--color-text-subtle)]">
                #{i + 1}
              </span>
              <input
                type="text"
                placeholder="0x… (empty = self)"
                value={r.address}
                disabled={readOnly}
                onChange={(e) => onUpdate(i, { address: e.target.value })}
                aria-label={`Recipient ${i + 1} address`}
                className="min-w-0 flex-1 rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 font-mono text-[11px] disabled:opacity-60"
              />
              <input
                type="text"
                placeholder="0.0"
                value={r.amount}
                disabled={readOnly}
                onChange={(e) => onUpdate(i, { amount: e.target.value })}
                aria-label={`Recipient ${i + 1} amount`}
                className="w-28 shrink-0 rounded border border-[var(--color-border-strong)] bg-white px-1.5 py-1 text-right font-mono font-semibold disabled:opacity-60"
              />
              {(() => {
                // Hide the button when totals aren't wired up or the
                // row already covers (or exceeds) the remainder.
                const rest = restFor(i);
                if (!rest || readOnly) return null;
                return (
                  <button
                    type="button"
                    onClick={() => onUpdate(i, { amount: rest })}
                    title={`Fill remaining ${rest}${amountSymbol ? ` ${amountSymbol}` : ""}`}
                    className="shrink-0 rounded border border-[var(--color-border-strong)] bg-[var(--color-bg)] px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-[var(--color-text-muted)] hover:border-[var(--color-primary)] hover:text-[var(--color-primary)]"
                  >
                    Rest
                  </button>
                );
              })()}
              {amountSymbol && (
                <span className="w-12 shrink-0 text-[10px] font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
                  {amountSymbol}
                </span>
              )}
              <button
                type="button"
                onClick={() => onRemove(i)}
                disabled={readOnly || rows.length <= 1}
                aria-label={`Remove recipient ${i + 1}`}
                className="shrink-0 rounded p-0.5 text-[var(--color-text-subtle)] hover:text-[var(--color-danger)] disabled:opacity-30"
              >
                ×
              </button>
            </div>

            {/* Compact metadata row — only renders when at least one
                optional column is enabled. Inline fields, smaller
                input height than the primary row to keep the visual
                weight on the address+amount line. */}
            {hasMetaLine && (
              <div className="mt-1 flex flex-wrap items-center gap-1.5 pl-7 text-[10px]">
                {showName && (
                  <label className="flex min-w-0 flex-1 basis-32 items-center gap-1">
                    <span className="uppercase tracking-wide text-[var(--color-text-subtle)]">Name</span>
                    <input
                      type="text"
                      placeholder="Optional"
                      value={r.name}
                      disabled={readOnly}
                      onChange={(e) => onUpdate(i, { name: e.target.value })}
                      aria-label={`Recipient ${i + 1} name`}
                      className="min-w-0 flex-1 rounded border border-[var(--color-border-strong)] bg-white px-1 py-0.5 disabled:opacity-60"
                    />
                  </label>
                )}
                {showEmail && (
                  <label className="flex min-w-0 flex-1 basis-44 items-center gap-1">
                    <span className="uppercase tracking-wide text-[var(--color-text-subtle)]">Email</span>
                    <input
                      type="email"
                      placeholder="optional@example.com"
                      value={r.email ?? ""}
                      disabled={readOnly}
                      onChange={(e) => onUpdate(i, { email: e.target.value })}
                      aria-label={`Recipient ${i + 1} email`}
                      className="min-w-0 flex-1 rounded border border-[var(--color-border-strong)] bg-white px-1 py-0.5 disabled:opacity-60"
                    />
                  </label>
                )}
                {showReleaseAt && (
                  <label className="flex min-w-0 flex-1 basis-44 items-center gap-1">
                    <span className="uppercase tracking-wide text-[var(--color-text-subtle)]">Claim from</span>
                    <input
                      type="datetime-local"
                      value={r.releaseAt ?? ""}
                      disabled={readOnly}
                      onChange={(e) => onUpdate(i, { releaseAt: e.target.value })}
                      aria-label={`Recipient ${i + 1} claim release time`}
                      className="min-w-0 flex-1 rounded border border-[var(--color-border-strong)] bg-white px-1 py-0.5 font-mono disabled:opacity-60"
                    />
                  </label>
                )}
              </div>
            )}

            {warning && (
              <p className="mt-1 pl-7 text-[10px] text-[var(--color-danger)]">{warning}</p>
            )}
          </div>
        );
      })}
      {!readOnly && rows.length < maxRows && (
        <button
          type="button"
          onClick={onAdd}
          className="rounded-md border border-dashed border-[var(--color-border-strong)] bg-white px-3 py-1.5 text-[11px] text-[var(--color-text-muted)] hover:border-[var(--color-primary)] hover:text-[var(--color-primary)]"
        >
          + Add recipient
        </button>
      )}
    </div>
  );
}

/** Display-string → base units. Throws on malformed input or
 *  fractional precision beyond `decimals` (mirrors the apps'
 *  `parseUnits` so Rest's math round-trips through submit). */
function parseDisplay(value: string, decimals: number): bigint {
  if (!/^\d+(\.\d+)?$/.test(value)) throw new Error("invalid");
  const [whole, frac = ""] = value.split(".");
  if (frac.length > decimals) throw new Error("too many decimals");
  const padded = frac.padEnd(decimals, "0");
  const wholeClean = whole!.replace(/^0+(?=\d)/, "");
  return BigInt(wholeClean + padded);
}

/** Base units → display string, trailing zeros trimmed so a
 *  whole-token rest renders as `"1000"` not `"1000.000000"`. */
function formatDisplay(value: bigint, decimals: number): string {
  const s = value.toString().padStart(decimals + 1, "0");
  const whole = s.slice(0, s.length - decimals);
  const frac = s.slice(s.length - decimals).replace(/0+$/, "");
  return frac ? `${whole}.${frac}` : whole;
}
